// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class columnafjecucionnfacturacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnafjecucionnfacturacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202006182102434_columnafjecucionnfacturacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
